#!/bin/bash

echo "${AMMAN_EXPORTS_CRON_TIME} OPENMRS_DB_SERVER=${OPENMRS_DB_SERVER} OPENMRS_DB_USERNAME=${OPENMRS_DB_USERNAME} OPENMRS_DB_PASSWORD=${OPENMRS_DB_PASSWORD} /bin/bash /usr/bin/bahmni-batch" | crontab -
