name: Trivy Security Scan
on:
  push:
    branches:
      - MOBN-2469
  workflow_dispatch:

jobs:
  security-scan:
    name: Run Trivy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Pull Github code
        uses: actions/checkout@v4
        
      - name: Build docker image
        run: docker build -t amman-exports:latest -f package/docker/Dockerfile .
        
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'amman-exports:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'library'
          trivyignores: ./.trivyignore
          severity: 'HIGH,CRITICAL'